### ISSUE TITLE
Move virtualenv dirs instead of deleting

### ISSUE THREAD

**Issue by hany** [vmfarms/deploy#1]
Instead of deleting virtualenv's on Django deployments, perhaps it should be moved out of the way to allow rollbacks, and to also ensure that the currently running app remains functional in case it needs access to any files under the existing virtualenv while the deploy is occurring:

https://github.com/vmfarms/deploy/blob/master/playbooks/django.yml#L28-L32

Even better is converting the "default" dir into a symlink to versioned virtualenv dirs.

**Comment by hany** [comment]
Ah, it looks like it does create a symlink after all. In this case, is it necessary to delete the symlink during deploy instead of just relying on the force symlinking at the end?

https://github.com/vmfarms/deploy/blob/master/playbooks/django.yml#L99-L104

**Comment by benvmfarms** [comment]
The delete step removes the default (Puppet-managed) directory entirely. It
will only delete it if is a directory (not a symlink).

You are right, though, that it should move it out of the way instead.

The main problem is that this is incompatible with existing deployments.
Puppet will need to be modified to not force rebuilding the default
virtualenv (and thus override the default symlink). This is something I did
not consider yesterday.

**Comment by hany** [comment]
I think Puppet will only rebuild if "something" doesn't exist at `/data/virtualenv/default`. If it exists, even as a symlink, it will not rebuild.
